name: CI and Release

on:
  pull_request:
    branches:
      - development
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --release

  release:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build release
        run: cargo build --release
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: Release from PR ${{ github.event.pull_request.title }}
          draft: false
          prerelease: false
          files: target/release/rust-command-line-todo-list
